# Generated by Django 4.2 on 2026-04-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('model_used', models.CharField(default='Advanced_Hybrid', max_length=50)),
                ('prediction', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('cnn_prediction', models.CharField(blank=True, max_length=20)),
                ('cnn_confidence', models.FloatField(blank=True, null=True)),
                ('rnn_prediction', models.CharField(blank=True, max_length=20)),
                ('rnn_confidence', models.FloatField(blank=True, null=True)),
                ('hybrid_prediction', models.CharField(blank=True, max_length=20)),
                ('hybrid_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
